project_id = "consulta-pps-uflo"

[api]
port = 55321

[db]
port = 55322
shadow_port = 55320
major_version = 17

[inbucket]
port = 55324
smtp_port = 55325
pop3_port = 55326

[functions.automated-backup]
verify_jwt = false

[functions.check-consentimiento-pendientes]
verify_jwt = false

[functions.generate-content]
verify_jwt = true

[functions.health-check]
verify_jwt = false

[functions.hermes-proxy]
verify_jwt = true

[functions.launch-scheduler]
verify_jwt = false

[functions.list-backups]
verify_jwt = true

[functions.moodle-autologin]
verify_jwt = true

[functions.request-password-reset]
verify_jwt = true

[functions.reset-password-with-token]
verify_jwt = true

[functions.restore-backup]
verify_jwt = true

[functions.send-email]
verify_jwt = true

[functions.send-consentimiento-final-reminders]
verify_jwt = true

[functions.send-fcm-notification]
verify_jwt = true

[functions.student-login]
verify_jwt = true
