-- Crear tabla para seguimiento de tareas de Todoist
-- Tabla: todoist_tasks

CREATE TABLE IF NOT EXISTS todoist_tasks (
  id BIGSERIAL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  todoist_task_id TEXT NOT NULL,
  pps_name TEXT NOT NULL,
  content TEXT NOT NULL,
  due_date TEXT,
  labels TEXT,
  priority INTEGER,
  completed_at TIMESTAMPTZ DEFAULT NOW(),
  institution_phone TEXT
);

-- Crear índice para búsqueda rápida
CREATE INDEX IF NOT EXISTS idx_todoist_task_id ON todoist_tasks(todoist_task_id);

-- Crear índice para búsqueda por nombre de PPS
CREATE INDEX IF NOT EXISTS idx_pps_name ON todoist_tasks(pps_name);

-- Crear índice para búsqueda por fecha
CREATE INDEX IF NOT EXISTS idx_due_date ON todoist_tasks(due_date);

-- Crear índice para búsqueda por estado completada
CREATE INDEX IF NOT EXISTS idx_completed_at ON todoist_tasks(completed_at);
