// Mock convocatorias across all states for Lanzador demo

const STATES = {
  borrador:     { key: 'borrador',     label: 'Borrador',         step: 1, action: 'Continuar editando', icon: 'edit_note' },
  abierta:      { key: 'abierta',      label: 'Inscripción abierta', step: 2, action: 'Ver inscriptos',   icon: 'how_to_reg' },
  cerrada:      { key: 'cerrada',      label: 'A seleccionar',    step: 3, action: 'Seleccionar',        icon: 'rule' },
  seleccionada: { key: 'seleccionada', label: 'A asegurar',       step: 4, action: 'Generar seguro',     icon: 'shield' },
  activa:       { key: 'activa',       label: 'Activa',           step: 5, action: 'Ver en gestión',     icon: 'play_arrow' },
  archivada:    { key: 'archivada',    label: 'Archivada',        step: 6, action: 'Reabrir o duplicar', icon: 'inventory_2' },
};

const STEPS = ['Crear', 'Inscripción', 'Seleccionar', 'Seguro', 'Activa'];

const INSTITUCIONES = [
  { id: 'i1', nombre: 'Hospital de Niños "Dr. R. Gutiérrez"', tipo: 'Hospital pediátrico', contacto: 'María González', tel: '+54 11 4962-9090', ultima: 'cohorte 2025 · 4 acreditados' },
  { id: 'i2', nombre: 'CONICET · INEBA',                       tipo: 'Centro de investigación', contacto: 'Dr. R. Fernández', tel: '+54 11 4523-9988', ultima: 'cohorte 2025 · 6 acreditados' },
  { id: 'i3', nombre: 'CESAC nº 8',                            tipo: 'Centro de salud comunitaria', contacto: 'Lic. Verónica Lopez', tel: '+54 11 4924-2105', ultima: 'cohorte 2024 · 5 acreditados' },
  { id: 'i4', nombre: 'Hospital Borda',                        tipo: 'Hospital psiquiátrico', contacto: 'Dr. P. Acuña', tel: '+54 11 4304-5555', ultima: 'cohorte 2023 · 3 acreditados' },
  { id: 'i5', nombre: 'Escuela Normal Sup. nº 6',              tipo: 'Escuela media', contacto: 'Prof. C. Yáñez', tel: '+54 11 4801-3344', ultima: 'cohorte 2025 · 5 acreditados' },
  { id: 'i6', nombre: 'Hospital Italiano',                     tipo: 'Hospital general', contacto: 'Dra. L. Méndez', tel: '+54 11 4959-0200', ultima: 'cohorte 2026-1 · activa' },
  { id: 'i7', nombre: 'Fundación Manantiales',                 tipo: 'ONG · adicciones',     contacto: 'Lic. F. Soto', tel: '+54 11 4801-0099', ultima: 'cohorte feb 2026 · 8 acreditados' },
];

const CONVOCATORIAS = [
  {
    id: 'c1', state: 'borrador',
    nombre: '', // unnamed draft
    institucion: null,
    createdAt: 'Hoy · 09:14',
    updatedAt: 'Hoy · 09:21',
    iaUsed: false,
    completion: 0.08,
  },
  {
    id: 'c2', state: 'borrador',
    nombre: 'PPS Clínica pediátrica · cohorte 2026-2',
    institucion: INSTITUCIONES[0],
    orientaciones: ['Clínica'],
    cupos: 4, horas: 80,
    direccion: 'Gallo 1330, CABA', online: false,
    fechaInicio: '01 ago 2026', fechaFin: '15 dic 2026',
    encuentroInicial: '28 jul 2026 · 18:00',
    inicioInscripcion: '10 jun 2026', cierreInscripcion: '25 jun 2026',
    horarios: [{ dia: 'Mar', desde: '14:00', hasta: '18:00', supervisor: 'Lic. M. González' }, { dia: 'Jue', desde: '14:00', hasta: '18:00', supervisor: 'Lic. M. González' }],
    horariosFijos: true,
    certTrabajo: true, solicitarCV: false,
    programarLanzamiento: false, fechaProgramada: '',
    requisitos: ['4to año o más', 'Aprobada Clínica I', 'Disponibilidad horaria estable'],
    requisitoExcluyente: 'Tener aprobada Psicopatología I',
    materialReferencia: 'Programa: Acompañamiento clínico en sala de internación pediátrica. Trabajo en equipo interdisciplinario, ateneos semanales, supervisión directa con jefa de servicio. 80 horas distribuidas en 16 semanas. Cupos: 4 estudiantes.',
    descripcion: 'Acompañamiento clínico en sala de internación pediátrica. Trabajo en equipo interdisciplinario, ateneos semanales, supervisión directa con jefa de servicio.',
    actividades: [
      'Observación y registro en sala de internación',
      'Participación en ateneos clínicos semanales',
      'Lectura supervisada de historias clínicas',
      'Devolución y cierre con familia (acompañamiento)',
    ],
    archivoUrl: '',
    archivoNombre: 'Fundamentación-PPS-Niños-2026-2.pdf',
    whatsappMsg: '',
    createdAt: 'Ayer · 16:00',
    updatedAt: 'Hoy · 10:32',
    iaUsed: true,
    completion: 0.82,
  },
  {
    id: 'c3', state: 'abierta',
    nombre: 'PPS Investigación II · cohorte 2026-2',
    institucion: INSTITUCIONES[1],
    orientaciones: ['Clínica', 'Educacional'],
    cupos: 6, inscriptos: 23,
    cierreEn: 'en 3 días',
    cierreFecha: '29 may',
    abiertaDesde: 'Lun 19 may',
    inscripcionTrend: [0,2,4,5,8,11,12,14,16,18,19,21,22,23],
    // breakdown per horario offered
    horarioBreakdown: [
      { id: 'h1', label: 'Lunes y Miércoles · 10 a 12', cuposLocal: 2, inscriptos: 14, status: 'over' },
      { id: 'h2', label: 'Martes y Jueves · 14 a 16',  cuposLocal: 2, inscriptos: 8,  status: 'on'   },
      { id: 'h3', label: 'Miércoles y Viernes · 14 a 16', cuposLocal: 2, inscriptos: 1,  status: 'low' },
    ],
    mix: {
      orientaciones: { 'Clínica': 11, 'Educacional': 9, 'Laboral': 2, 'Comunitaria': 1 },
      anios:         { '5to': 14, '4to': 8, '3ro': 1 },
      conPPSPrevia: 12,
    },
    difusion: [
      { canal: 'whatsapp', cuando: 'Lun 19 may · 09:14', detalle: 'Posteo en grupo PPS Psico UFLO', desde: 12 },
      { canal: 'mail',     cuando: 'Lun 19 may · 10:02', detalle: 'Mail a lista cohorte 2026',     desde: 7  },
      { canal: 'whatsapp', cuando: 'Vie 23 may · 17:30', detalle: 'Recordatorio en grupo',         desde: 4  },
    ],
    ultimos: [
      { name: 'Sofía Pereyra',    year: '5to año', when: 'hace 14 min', horario: 'Lunes y Miércoles · 10 a 12', tags: ['cursando electivas','whatsapp'] },
      { name: 'Marcos Rodríguez', year: '4to año', when: 'hace 2 h',    horario: 'Martes y Jueves · 14 a 16',  tags: ['whatsapp'] },
      { name: 'Lucía Bertinotti', year: '5to año', when: 'hace 3 h',    horario: 'Lunes y Miércoles · 10 a 12', tags: ['cursando electivas','tfi','whatsapp'] },
      { name: 'Federico Larrea',  year: '5to año', when: 'hace 5 h',    horario: 'Martes y Jueves · 14 a 16',  tags: ['trabaja','whatsapp'] },
      { name: 'Camila Ruiz',      year: '4to año', when: 'ayer',         horario: 'Lunes y Miércoles · 10 a 12', tags: ['whatsapp'] },
      { name: 'Joaquín Suárez',   year: '5to año', when: 'ayer',         horario: 'Lunes y Miércoles · 10 a 12', tags: ['cursando electivas'] },
    ],
  },
  {
    id: 'c4', state: 'abierta',
    nombre: 'PPS Comunitaria · CESAC 8',
    institucion: INSTITUCIONES[2],
    orientaciones: ['Comunitaria'],
    cupos: 8, inscriptos: 12,
    cierreEn: 'mañana',
    cierreFecha: '27 may',
    abiertaDesde: 'Mié 14 may',
    inscripcionTrend: [0,1,2,3,4,5,6,7,8,9,10,11,12,12],
    ultimos: [
      { name: 'Tomás Mansilla',  year: '5to año', when: 'hace 6 h' },
      { name: 'Camila Vidal',    year: '4to año', when: 'ayer' },
    ],
  },
  {
    id: 'c5', state: 'cerrada',
    nombre: 'Supervisión de Educación Primaria (Alto Valle Este I – Zona I)',
    institucion: INSTITUCIONES[4],
    orientaciones: ['Educacional'],
    cupos: 2, inscriptos: 12,
    cerradaHace: 'hace 2 días',
    fechaCierre: '24 may',
    horariosOptions: ['Lunes y Miércoles de 10 a 12', 'Martes y Jueves de 10 a 12', 'Miércoles y Viernes de 14 a 16'],
    candidatos: [
      {
        id: 's1', name: 'Camila Rocío Bertoldi',
        score: 179, hsAcum: 217, year: '5to',
        tags: ['CURSANDO ELECTIVAS', 'TRABAJA', 'WHATSAPP'],
        nota: 'Estoy elaborando mi TFI. Cursando las últimas 2 materias se orientación. Necesito esta rotación a esta orientación por favor.',
        horarioElegido: 'Martes y Jueves de 10 a 12',
        compromiso: { estado: 'confirmado', fecha: '13/05/2026', hora: '08:38 a.m.' },
        whatsapp: '+54 9 299 555-1212',
        selected: 'in',
        aiReason: 'Score muy alto (179), TFI en marcha, horario sin conflictos, ya tiene WhatsApp registrado.',
      },
      {
        id: 's2', name: 'Ana Paula Funes Citati',
        score: 121, hsAcum: 142, year: '5to',
        tags: ['CURSANDO ELECTIVAS', 'WHATSAPP'],
        nota: 'Cursando las últimas dos materias del área educacional de forma asincrónica, por lo que cuento con disponibilidad horaria.',
        horarioElegido: 'Martes y Jueves de 10 a 12',
        compromiso: { estado: 'confirmado', fecha: '13/05/2026', hora: '08:43 a.m.' },
        whatsapp: '+54 9 299 555-3344',
        selected: 'in',
        aiReason: 'Cursando últimas materias educacional. Confirmada apenas se le ofreció.',
      },
      {
        id: 's3', name: 'Ester Jocabed Naama Valenzuela',
        score: 98, hsAcum: 95, year: '4to',
        tags: ['CURSANDO ELECTIVAS', 'WHATSAPP'],
        nota: 'Necesito urgente practicas de mi orientacion, necesito recibirme este año.',
        horarioElegido: 'Martes y Jueves de 10 a 12',
        compromiso: null,
        whatsapp: '+54 9 299 555-7788',
        selected: null,
        conflict: 'Tiene otra PPS de Investigación los martes 14-18 (sin choque)',
      },
      {
        id: 's4', name: 'Mariano Andres Muñoz',
        score: 90, hsAcum: 80, year: '4to',
        tags: ['CURSANDO ELECTIVAS', 'WHATSAPP'],
        nota: 'Cursando materias electivas de la orientación educacional.',
        horarioElegido: 'Martes y Jueves de 10 a 12',
        compromiso: null,
        whatsapp: '+54 9 299 555-9911',
        selected: null,
      },
      {
        id: 's5', name: 'Sol Amusategui',
        score: 90, hsAcum: 80, year: '4to',
        tags: ['CURSANDO ELECTIVAS', 'WHATSAPP'],
        nota: '',
        horarioElegido: 'Martes y Jueves de 10 a 12',
        compromiso: null,
        whatsapp: '+54 9 299 555-2233',
        selected: null,
      },
      {
        id: 's6', name: 'Pilar Ruíz',
        score: 76, hsAcum: 64, year: '4to',
        tags: ['WHATSAPP'],
        nota: 'Quería preguntar si puedo hacer un horario flexible, trabajo medio tiempo.',
        horarioElegido: 'Miércoles y Viernes de 14 a 16',
        compromiso: null,
        whatsapp: '+54 9 299 555-4477',
        selected: null,
        conflict: 'Pidió horario distinto al ofrecido',
      },
      {
        id: 's7', name: 'Federico Larrea',
        score: 72, hsAcum: 70, year: '5to',
        tags: ['TRABAJA'],
        nota: 'Trabajo de 9 a 13, podría a la tarde.',
        horarioElegido: '',
        compromiso: null,
        whatsapp: '',
        selected: null,
        conflict: 'No tiene WhatsApp registrado · trabajo en franja matutina',
      },
      {
        id: 's8', name: 'Tomás Mansilla',
        score: 68, hsAcum: 60, year: '4to',
        tags: ['CURSANDO ELECTIVAS', 'WHATSAPP'],
        nota: '',
        horarioElegido: 'Lunes y Miércoles de 10 a 12',
        compromiso: null,
        whatsapp: '+54 9 299 555-6655',
        selected: null,
        conflict: 'Eligió horario que no ofrecemos en esta PPS',
      },
    ],
  },
  {
    id: 'c6', state: 'seleccionada',
    nombre: 'PPS Educacional · Esc. Normal 6',
    institucion: INSTITUCIONES[4],
    orientaciones: ['Educacional'],
    cupos: 5, seleccionados: 5,
    pasoSeguro: 2,
    seguroSteps: [
      { k: 'datos',       label: 'Datos personales verificados',   status: 'done' },
      { k: 'planilla',    label: 'Planilla generada (PDF)',         status: 'done' },
      { k: 'aseguradora', label: 'Envío a aseguradora · LaCaja',    status: 'active' },
      { k: 'confirm',     label: 'Confirmación de pólizas',         status: 'pending' },
      { k: 'cierre',      label: 'Aviso a estudiantes',             status: 'pending' },
    ],
    // Consentimiento phase — happens BEFORE seguro
    // estado: 'firmado' | 'pendiente' | 'baja' (timeout)
    consentimientos: [
      { name: 'Renata Páez',       dni: '40.221.998', estado: 'firmado',   firmadoEn: 'Ayer 18:12', enviadoEn: 'Ayer 14:00', deadline: 'Hoy 14:00' },
      { name: 'Joaquín Suárez',    dni: '41.018.302', estado: 'firmado',   firmadoEn: 'Hoy 09:48',  enviadoEn: 'Ayer 14:00', deadline: 'Hoy 14:00' },
      { name: 'Maite Falcón',      dni: '40.998.776', estado: 'pendiente', firmadoEn: null, enviadoEn: 'Ayer 14:00', deadline: 'Hoy 14:00', horasRestantes: 3.5 },
      { name: 'Bruno Castillo',    dni: '41.220.554', estado: 'pendiente', firmadoEn: null, enviadoEn: 'Ayer 14:00', deadline: 'Hoy 14:00', horasRestantes: 3.5 },
      { name: 'Agustina Veronesi', dni: '40.776.001', estado: 'firmado',   firmadoEn: 'Ayer 16:34', enviadoEn: 'Ayer 14:00', deadline: 'Hoy 14:00' },
    ],
    alumnos: [
      { name: 'Renata Páez',       dni: '40.221.998', seguro: 'pendiente' },
      { name: 'Joaquín Suárez',    dni: '41.018.302', seguro: 'pendiente' },
      { name: 'Maite Falcón',      dni: '40.998.776', seguro: 'pendiente' },
      { name: 'Bruno Castillo',    dni: '41.220.554', seguro: 'pendiente' },
      { name: 'Agustina Veronesi', dni: '40.776.001', seguro: 'pendiente' },
    ],
  },
  {
    id: 'c7', state: 'activa',
    nombre: 'PPS Clínica · Hospital Italiano',
    institucion: INSTITUCIONES[5],
    orientaciones: ['Clínica'],
    activos: 4, total: 4,
    inicio: '01 abril', fin: '31 mayo',
    estadoGestion: 'Por finalizar (5 días)',
    progresoHoras: 0.86,
  },
  {
    id: 'c8', state: 'activa',
    nombre: 'PPS Investigación I · cohorte 2026-1',
    institucion: INSTITUCIONES[1],
    orientaciones: ['Clínica', 'Educacional'],
    activos: 6, total: 6,
    inicio: '15 marzo', fin: '15 julio',
    estadoGestion: 'En curso · sin novedades',
    progresoHoras: 0.51,
  },
  {
    id: 'c10', state: 'archivada',
    nombre: 'PPS Laboral · Manantiales',
    institucion: INSTITUCIONES[6],
    archivadaEn: 'feb 2026',
    motivo: 'Cerró ciclo · 8 alumnos acreditados',
    completedSuccess: true,
    cohorte: '2025-2',
    inscriptos: 14, seleccionados: 8, acreditados: 8,
    lifeline: [
      { fecha: 'sep 2025', kind: 'lanzada', label: 'Convocatoria lanzada' },
      { fecha: 'sep 2025', kind: 'cierre',  label: 'Cierre · 14 inscriptos · sobre cupo 1.75×' },
      { fecha: 'sep 2025', kind: 'select',  label: '8 seleccionados · todos firmaron consentimiento' },
      { fecha: 'oct 2025', kind: 'inicio',  label: 'Práctica iniciada' },
      { fecha: 'feb 2026', kind: 'cierre',  label: '8 acreditados · 0 bajas · cierre académico' },
    ],
    participantes: [
      { name: 'Luciana Acuña',    dni: '40.111.222', outcome: 'acreditado', hs: 80 },
      { name: 'Tomás Espósito',   dni: '40.222.333', outcome: 'acreditado', hs: 80 },
      { name: 'Pilar Méndez',     dni: '40.333.444', outcome: 'acreditado', hs: 80 },
      { name: 'Esteban Ortiz',    dni: '40.444.555', outcome: 'acreditado', hs: 80 },
      { name: 'Florencia Núñez',  dni: '40.555.666', outcome: 'acreditado', hs: 80 },
      { name: 'Diego Lerner',     dni: '40.666.777', outcome: 'acreditado', hs: 80 },
      { name: 'Mariana Carrizo',  dni: '40.777.888', outcome: 'acreditado', hs: 80 },
      { name: 'Iván Garrido',     dni: '40.888.999', outcome: 'acreditado', hs: 80 },
    ],
    insights: [
      { kind: 'good',  text: 'Cohorte perfecta: 0 bajas, todos completaron 80 hs. Mantener el formato.' },
      { kind: 'tip',   text: 'La aseguradora demoró 5 días — empezar el trámite 1 semana antes.' },
    ],
  },
  {
    id: 'c11', state: 'archivada',
    nombre: 'PPS Educacional · Esc. Normal 6',
    institucion: INSTITUCIONES[4],
    archivadaEn: 'dic 2025',
    motivo: 'Cerró ciclo · 4 acreditados',
    completedSuccess: true,
    cohorte: '2025-2',
    inscriptos: 11, seleccionados: 4, acreditados: 4,
    lifeline: [
      { fecha: 'ago 2025', kind: 'lanzada', label: 'Convocatoria lanzada' },
      { fecha: 'ago 2025', kind: 'cierre',  label: 'Cierre · 11 inscriptos · 2.75× cupo' },
      { fecha: 'ago 2025', kind: 'select',  label: '4 seleccionados · 1 no firmó (baja auto)' },
      { fecha: 'ago 2025', kind: 'select',  label: 'Reseleccionado: ingresó Camila V. de la lista de espera' },
      { fecha: 'sep 2025', kind: 'inicio',  label: 'Práctica iniciada' },
      { fecha: 'dic 2025', kind: 'cierre',  label: '4 acreditados' },
    ],
    participantes: [
      { name: 'Sebastián Roca',  dni: '40.101.202', outcome: 'acreditado', hs: 80 },
      { name: 'Camila Villar',   dni: '40.202.303', outcome: 'acreditado', hs: 80, nota: 'Ingresó por reselección' },
      { name: 'Lautaro Páez',    dni: '40.303.404', outcome: 'acreditado', hs: 80 },
      { name: 'Antonella Soto',  dni: '40.404.505', outcome: 'acreditado', hs: 80 },
      { name: 'Mateo Cabrera',   dni: '40.505.606', outcome: 'baja',       hs: 0,  nota: 'No firmó consentimiento en 24 hs' },
    ],
    insights: [
      { kind: 'warn', text: 'Mateo C. no firmó consentimiento — perdimos 24hs antes de poder reseleccionar.' },
      { kind: 'tip',  text: 'Considerar bajar el plazo de consentimiento a 12 hs o reasignar más rápido desde la lista de espera.' },
    ],
  },
  {
    id: 'c12', state: 'archivada',
    nombre: 'PPS Clínica · Hospital de Niños',
    institucion: INSTITUCIONES[0],
    archivadaEn: 'nov 2025',
    motivo: 'Cerró ciclo · 4 acreditados',
    completedSuccess: true,
    cohorte: '2025-2',
    inscriptos: 22, seleccionados: 4, acreditados: 4,
    lifeline: [
      { fecha: 'jul 2025', kind: 'lanzada', label: 'Convocatoria lanzada' },
      { fecha: 'jul 2025', kind: 'cierre',  label: 'Cierre · 22 inscriptos · 5.5× cupo' },
      { fecha: 'jul 2025', kind: 'select',  label: '4 seleccionados · todos firmaron' },
      { fecha: 'ago 2025', kind: 'inicio',  label: 'Práctica iniciada' },
      { fecha: 'nov 2025', kind: 'cierre',  label: '4 acreditados · cierre académico' },
    ],
    participantes: [
      { name: 'Valentina Aliaga', dni: '40.121.232', outcome: 'acreditado', hs: 80 },
      { name: 'Nicolás Rey',      dni: '40.232.343', outcome: 'acreditado', hs: 80 },
      { name: 'Mora Quiroga',     dni: '40.343.454', outcome: 'acreditado', hs: 80 },
      { name: 'Federico Vega',    dni: '40.454.565', outcome: 'acreditado', hs: 80 },
    ],
    insights: [
      { kind: 'good', text: 'Sobre demanda alta (5.5×) — institución consolidada para esta orientación.' },
      { kind: 'tip',  text: 'Considerar abrir 2 PPS paralelas el próximo año o aumentar cupos a 6.' },
    ],
  },
  {
    id: 'c9', state: 'archivada',
    nombre: 'PPS Comunitaria · Posadas',
    institucion: { nombre: 'CESAC Posadas', tipo: 'Centro de salud comunitaria' },
    archivadaEn: 'mayo 2025',
    motivo: 'Sin cupo · institución cerró convocatoria',
    completedSuccess: false,
    cohorte: '2025-1',
    inscriptos: 5, seleccionados: 0,
    lifeline: [
      { fecha: 'mar 2025', kind: 'lanzada', label: 'Convocatoria lanzada' },
      { fecha: 'abr 2025', kind: 'cierre',  label: 'Cierre · 5 inscriptos · bajo cupo (0.83×)' },
      { fecha: 'abr 2025', kind: 'pausa',   label: 'Institución pidió pausar — sin respuesta' },
      { fecha: 'may 2025', kind: 'cierre',  label: 'Archivada · sin selección posible' },
    ],
    participantes: [
      { name: 'Lara Pérez',     dni: '40.aaa.bbb', outcome: 'no-selec', hs: 0 },
      { name: 'Joaquín M.',     dni: '40.ccc.ddd', outcome: 'no-selec', hs: 0 },
      { name: 'Sofía L.',       dni: '40.eee.fff', outcome: 'no-selec', hs: 0 },
      { name: 'Diego R.',       dni: '40.ggg.hhh', outcome: 'no-selec', hs: 0 },
      { name: 'Carla T.',       dni: '40.iii.jjj', outcome: 'no-selec', hs: 0 },
    ],
    insights: [
      { kind: 'warn', text: 'Institución no respondió 3 emails de seguimiento. Reagendar contacto en sep 2025.' },
      { kind: 'tip',  text: 'PPS Comunitaria en Posadas: baja demanda local. Considerar PPS virtual o eliminar oferta.' },
    ],
  },
];

const ORIENTACIONES = ['Clínica', 'Educacional', 'Laboral', 'Comunitaria'];

Object.assign(window, { STATES, STEPS, INSTITUCIONES, CONVOCATORIAS, ORIENTACIONES });
